### ISSUE TITLE
[Cleanup] Merge RegisterAllType methods into 1 system

### ISSUE THREAD

**Issue by michaelsakharov** [michaelsakharov/Prowl#108]
We have a few static methods like RegisterAllMenus() and stuff that loop over all assemblies and register Attributes found in a dictionary. They also have a Clear() since they get cleared and re-registered on scripts reloading since they can contain said attributes.

It would be nice to have some singular source that handles finding attribute types

Maybe like
AttributeHolder.Clear();
AttributeHolder.GetAll<SomeAttribute>()
AttributeHolder.GetAllOnClass<SomeAttribute>()
AttributeHolder.GetAllOnField<SomeAttribute>()

Ones like GetAllOnField can cache the attributes on the field.

Not 100% sure how this would work, just thought about it as i just added yet another RegisterAll attributes method for the new PropertyDrawer stuff im working on

**Comment by michaelsakharov** [comment]
Added OnAssemblyLoad and OnAssemblyUnload Attributes

**Comment by PaperPrototype** [comment]
0.o noice
