### ISSUE TITLE
[Editor] (MacOS) crash when clicking "AssetBrowser"

### ISSUE THREAD

**Issue by PaperPrototype** [michaelsakharov/Prowl#118]
**Describe the bug**
Open Prowl on MacOS

**To Reproduce**
1. Create a new Project and try to click on the AssetBrowser window
2. It crashes

**Expected behavior**
You should be able to browse assets and see little icons for each one.

**Comment by PaperPrototype** [comment]
o.0

**Comment by michaelsakharov** [comment]
Pretty sure we fixed this? Or did we not?

**Comment by PaperPrototype** [comment]
I click it, and prowl goes bye bye

**Comment by michaelsakharov** [comment]
@all-contributors
please add @PaperPrototype.

**Comment by michaelsakharov** [comment]
@all-contributors
please add @<username> for help with MacOS support.

**Comment by michaelsakharov** [comment]
https://github.com/all-contributors
please add @PaperPrototype for help with MacOS support.

**Comment by michaelsakharov** [comment]
@all-contributors
please add @PaperPrototype for help with MacOS support.

**Comment by michaelsakharov** [comment]
@ll-contributors
please add @PaperPrototype for platform

**Comment by michaelsakharov** [comment]
@all-contributors
please add @PaperPrototype for platform

**Comment by michaelsakharov** [comment]
@all-contributors
please add @PaperPrototype for platform

**Comment by michaelsakharov** [comment]
god damnit you stoopid bot
