### ISSUE TITLE
[Editor] Basic 2D Support

### ISSUE THREAD

**Issue by michaelsakharov** [michaelsakharov/Prowl#23]
- [ ] Ensure Orthographic Camera's work correctly in all areas
- [ ] Scene view Orthographic view
- [ ] 2D Sprite
  - [ ] Single & Multi Sprites
  - [ ] Origin/Center Offset
- [ ] Sprite Renderer & Texture Renderer

**Comment by michaelsakharov** [comment]
I've decided im not gonna put in effort for 2D
Atleast not for the time being

Theres already many amazing 2D engines, even many open source c# ones like Duality.
Thats not where prowl should be focusing its time, its a 3D engine, 2D is naturally supported simply due to the nature of Prowl but I'm not gonna put in extra effort like a Tilemap or Sprite System for now, maybe later after Prowl is more then useable and stable.

**Comment by nightblade9** [comment]
Can you please update your GitHub tags and website to mention this? I keep finding Prowl while looking for 2D engines.

What are some of the amazing ones you like? Duality looks dead.

**Comment by michaelsakharov** [comment]
> Can you please update your GitHub tags and website to mention this? I keep finding Prowl while looking for 2D engines.
> 
> What are some of the amazing ones you like? Duality looks dead.

I don't believe any tags or anything say we have 2D support, and we don't even have a website.

Even Godot is technically a 2D focused open source engine with 3D slapped on.
Duality, Game Maker, Construct, LOVE, Phaser, Raylib (also has 3D), Pygame, RPG maker.
The list of good 2D engines is endless.

If you don't mind me asking where are you finding us? We haven't actively advertised or anything so I'm curious where your finding us.

**Comment by nightblade9** [comment]
I honestly don't remember. I've been searching for C# 2D game engines for a while, and your repo popped up a few times.
