### ISSUE TITLE
[Editor] Model importing scale

### ISSUE THREAD

**Issue by michaelsakharov** [michaelsakharov/Prowl#26]
FBX files and some others seem to import with drastically weird scales
Seems to be related to: https://github.com/assimp/assimp/issues/2166

**Comment by 10xJosh** [comment]
Ill look into this one, hopefully it goes a bit more smoothly than the other bug 😅

**Comment by michaelsakharov** [comment]
Awesome thanks!
It seems Assimp provides some sort of Unit Scale modifier we can use to scale the models on import.

It would be done inside ModelImporter.cs
Probably on the RootNode/Gameobject which is created around 258, just do 
rootNode.Scale = something
Im not sure how exactly to extract the unit scale from assimp though or how it works.

**Comment by michaelsakharov** [comment]
Let me know if you need a some models to test

**Comment by 10xJosh** [comment]
> Awesome thanks! It seems Assimp provides some sort of Unit Scale modifier we can use to scale the models on import.
> 
> It would be done inside ModelImporter.cs Probably on the RootNode/Gameobject which is created around 258, just do rootNode.Scale = something Im not sure how exactly to extract the unit scale from assimp though or how it works.
> 
> Reading the issue i linked above it might be something like: scene.Metadata["UnitScaleFactor"].Data;

I tried adding the rootnode stuff but im not sure it worked. I'll have to look more into it tomorrow, I'm a little in over my head here but ill figure it out.

How have you been importing the objects? I've just been putting it in the folder and going into the editor and dragging and dropping. Is there another way to import?

**Comment by michaelsakharov** [comment]
That is the correct way, for now, you might have to restart the editor for it to properly import the model.

**Comment by michaelsakharov** [comment]
Might be more to this then I initially thought.

**Comment by michaelsakharov** [comment]
Added a GlobalScale flag for ModelImporter which may help some cases
Also added a UnitScale modifier value like unity has, this doesn't solve the issue entirely, but it provides a decent enough solution.
