### ISSUE TITLE
[Editor] Reimporting assets doesnt always properly refresh the asset

### ISSUE THREAD

**Issue by michaelsakharov** [michaelsakharov/Prowl#28]

**Comment by 10xJosh** [comment]
Did this get fixed?

**Comment by michaelsakharov** [comment]
Not too sure, its possible it was fixed as a side effect of another fix, as i've done a few fixes that could connect to this.
 Ill check again and come up with a reproducable case.

**Comment by michaelsakharov** [comment]
yeah this appears to be fixed
