### ISSUE TITLE
[AssetPipeline] Prefabs/Scenes

### ISSUE THREAD

**Issue by michaelsakharov** [michaelsakharov/Prowl#3]
Taking from Godot, Prefabs and Scenes will be the same thing, just a GameObject with its children.
So we need to support Prefabs as well as supporting Nested Prefabs.

**Comment by michaelsakharov** [comment]
We need a way to track the changes between the Prefab and the Asset
so we can Apply/Reset individual changes

**Comment by michaelsakharov** [comment]
After much consideration
I think I'm sticking with the more unity structure over Godot's

I've been thinking too hard about this, Prowl's ultimate goal is to be a general replacement for unity, something that can take on existing unity projects without having to learn a new structure.

Dropping the Scene structure for an all prefab/gameobject route, i think goes too far outside the goals of the engine.
So ill be splitting this issue into 2 halves, Scenes & Prefabs individually.

**Comment by PaperPrototype** [comment]
👍
