### ISSUE TITLE
.obj Files Are Missing In "Default Assets" Folder; Includes File Is Missing As Well

### ISSUE THREAD

**Issue by 10xJosh** [michaelsakharov/Prowl#50]
**Describe the bug**
I forked the repository and cloned it to my computer using Visual Studio. When I ran it I got an error that said the cube.obj object couldn't be found.

When I look in the solution explorer I see a few .obj files that are outlined with a red X.

**To Reproduce**
1. Fork repository
2. Open Visual Studio, Clone repo to computer
3. Run project

**Expected behavior**
Should load the editor without issue

**Screenshots**
![2023-11-23 10_07_35-Prowl - Microsoft Visual Studio](https://github.com/michaelsakharov/Prowl/assets/55113224/7caa1402-833a-40d2-b254-2fbfd412ad59)

![2023-11-23 10_03_56-](https://github.com/michaelsakharov/Prowl/assets/55113224/c4d4995b-f755-46b1-87f3-30aaccc41231)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Visual Studio Version 17.8.0

**Additional context**
Looking at the files on Github, I noticed they were missing as well. No .obj can be found nor "Includes" folder: https://github.com/michaelsakharov/Prowl/tree/main/Prowl.Editor/EmbeddedResources/DefaultAssets

**Comment by 10xJosh** [comment]
sorry accidentally posted this too early... I didn't know shift+enter will send posts...

**Comment by 10xJosh** [comment]
Joined the discord, you're all aware of the issue + this is apparently a duplicate for the same issue. sorry!

**Comment by PaperPrototype** [comment]
> Joined the discord, you're all aware of the issue + this is apparently a duplicate for the same issue. sorry!

It's ok, it's great to see someone else on here :) maybe link the issue's #49
