### ISSUE TITLE
[Editor] Program Crashes If File In Asset Browser is Updated Using Visual Studio

### ISSUE THREAD

**Issue by 10xJosh** [michaelsakharov/Prowl#66]
**Describe the bug**
I ran into this issue when trying to figure out how to use the .cs scripts on game components. When I make any change and save the change in Visual Studio, it throws an error that can be found in the screenshot below.

**To Reproduce**
1. Launch Visual Studio
2. Create a .cs file in one of the projects folder for Prowel ( C:/Users/<username>/Documents/Prowl/Projects/ )
3. Start Debugging Prowl
4. Open a .cs script and edit it
5. Save the script

**Expected behavior**
No Crash, just updated script

**Screenshots**
![2023-11-28 21_34_11-Prowl (Debugging) - Microsoft Visual Studio](https://github.com/michaelsakharov/Prowl/assets/55113224/0513a1f3-b005-4469-a26d-adbe01bf4266)

**Additional context**
Right before making this issue, I tested this with other text editors, Notepad and Visual Studio Code updated the files fine without issue. This might be an issue with Visual Studio itself when debugging. Figured might as well report it for the record :)

**Comment by michaelsakharov** [comment]
Not sure how else to solve this other than to ignore missing files.

Can you check if 41747a5 fixed the issue?

**Comment by michaelsakharov** [comment]
It seems visual studio might just be generating random files, In which case that commit should fix it.

**Comment by 10xJosh** [comment]
I'll have to look into this tomorrow but I'll let you know as soon as i can

**Comment by 10xJosh** [comment]
Ok I tested it and looks like issue has been fixed! Thanks!
