### ISSUE TITLE
[Editor] AssetsWindow.Ping(Guid) - Asset Pinging

### ISSUE THREAD

**Issue by michaelsakharov** [michaelsakharov/Prowl#71]
Ping an asset to show the user were it is in the AssetsWindow and AssetBrowser

**Comment by 10xJosh** [comment]
I can do this one, was there a specific way you wanted this implemented?

**Comment by 10xJosh** [comment]
Yo.. my bad man I don't think I can do this one. I've been trying to wrap my head around the ImGui stuff for a while now and I'm not comfortable enough to propose any real change to implement this feature. Very sorry!

**Comment by michaelsakharov** [comment]
Added https://gyazo.com/67b42cf80dc3b4e1bdbd5d3af28bc090.mp4
