### ISSUE TITLE
[Engine] SceneObjects

### ISSUE THREAD

**Issue by michaelsakharov** [michaelsakharov/Prowl#95]
Removing Transforms on Gameobjects is becoming a bit confusing, it's weird to use and it's not particularly fast with things like Inheritance.

So after some pondering, we have another idea
We Leave GameObjects as is like in unity, instead of optional transforms, we move Scene stuff to a SceneObject which GameObject inherits.
A GameObject is just a fancy SceneObject with a Transform and a Component List.

Then you can in code Inherit a SceneObject and implement your own, much like a ScriptableObject.
That way if you want like a Game Manager and it doesn't need a transform, you can implement it as a SceneObject
This also prevents it from being turned off/on, can remove the need for Layers/tags, and so on, all that is specific to GameObjects

**Comment by PaperPrototype** [comment]
Love it

**Comment by michaelsakharov** [comment]
The more I think about this the more complications come up

At least for now I think this is outside the scope of the project :(

**Comment by PaperPrototype** [comment]
:( okie, at least I can access the physics engine directly without using gameObjects :P
